Add location
NINAnor/birdnet2sqlite pull request #1
Opened 2022-08-22 07:39 UTC by BenCretois

2022-08-22 08:54 UTC, frafra requested changes

2022-08-22 08:54 UTC, frafra commented on README.md
> +OUT_FOLDER=XXX
I would suggest to use command line parameters instead of `XXX` as placeholder, like `$1` and `$2`.

2022-08-22 08:54 UTC, frafra commented on README.md
> +For more flexibility with the script
Wouldn't be better to store the script in the repository as a standalone file instead of pasting it inside the README file?

2022-08-22 08:54 UTC, frafra commented on README.md
> +
What about having safeguards, such `set -euo pipefail`?

2022-08-22 08:54 UTC, frafra commented on README.md
> +# Use the database in R
What about having an `examples/` folder with these snippets and refer to them in the `README.md` file? The README file is a good solution for very short snippets of code, in my opinion, while larger ones could be better stored as files.

2022-08-22 08:54 UTC, frafra commented on birdnet2sqlite.py
> +        location = filename.split("/")[-2]
`os.path.dirname`?

2022-08-26 13:00 UTC, frafra requested changes

2022-08-26 13:00 UTC, frafra commented on Dockerfile
> +    pip install sqlite-utils
You can avoid using tools like pdm or poetry, but if you do that, please pin your dependency to a specific version, like `sqlite-utils==3.26.1` or specify a compatible version, such as `sqlite-utils~=3.26.1` (see also https://peps.python.org/pep-0440/#compatible-release).
Using a compatibility-like approach would make the Dockerfile lesser reproducible. This is why you usually have two files: one for the dependencies (containing version ranges) and pinned dependencies (for testing and reproducibility).

2022-08-26 13:00 UTC, frafra commented on Dockerfile
> +COPY --chmod=755 preprocess_birdnet_result.py ./
You can copy the files in one step to reduce the number of layers (micro-optimization).

2022-08-26 13:00 UTC, frafra commented on birdnet2sqlite.py
> +recorder_filename_date = re.compile(r"\d{8}_\d{6}.BirdNET.selection.table.txt")
This variable is not used anywhere else.

2022-08-26 13:00 UTC, frafra commented on birdnet2sqlite.py
> +        dt = datetime.datetime.strptime(matches.group(0), "%Y%m%d_%H%M%S.BirdNET.selection.table.txt")
You can refer to the `recorder_filename_date` variable here.

2022-08-26 13:00 UTC, frafra commented on birdnet2sqlite.py
> +        dt = datetime.datetime.strptime(matches.group(0), "%Y%m%d_%H%M%S.BirdNET.selection.table.txt")
You can use `$` at the end of your regex to be sure you are matching the end of your filename.

2022-09-02 11:48 UTC, BenCretois commented on birdnet2sqlite.py
> +        location = filename.split("/")[-2]
Mmhh it gives the entire path to the folder, then it's basically the same except that it would be `dirname.split("/")[-1]`

2022-09-05 10:06 UTC, BenCretois commented on README.md
> +# Use the database in R
It should now be simple enough so that there is no need for examples. And the use of ``birdnet2sqlite.sh` is now fully explained in the README

2022-10-21 10:19 UTC, merged